services:
  mongo:
    image: mongo:4.4
    env_file: .env
    volumes:
      - trials:/data/db

  open-box:
    build:
      context: .
      dockerfile: services/open-box.Dockerfile
    env_file: .env
    depends_on:
      - mongo
    ports:
      - 8000:8000
    expose:
      - "8000"

  postgres:
    image: postgres
    env_file: .env

volumes:
  trials:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./trials
